//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///   o 
        ///  /|\
        ///  / \
        ///.
        /// </summary>
        internal static string AnimationMessage0 {
            get {
                return ResourceManager.GetString("AnimationMessage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///  \o/
        ///   |  
        ///  / \ 
        ///.
        /// </summary>
        internal static string AnimationMessage1 {
            get {
                return ResourceManager.GetString("AnimationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///  _ o 
        ///   /\ 
        ///  | \ 
        ///.
        /// </summary>
        internal static string AnimationMessage2 {
            get {
                return ResourceManager.GetString("AnimationMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///       
        ///   __\o
        ///  /) | 
        ///.
        /// </summary>
        internal static string AnimationMessage3 {
            get {
                return ResourceManager.GetString("AnimationMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///  __|  
        ///    \o 
        ///    ( \
        ///.
        /// </summary>
        internal static string AnimationMessage4 {
            get {
                return ResourceManager.GetString("AnimationMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///    \ /
        ///     | 
        ///    /o\
        ///.
        /// </summary>
        internal static string AnimationMessage5 {
            get {
                return ResourceManager.GetString("AnimationMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///       |__ 
        ///     o/    
        ///    / )    
        ///.
        /// </summary>
        internal static string AnimationMessage6 {
            get {
                return ResourceManager.GetString("AnimationMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///         
        ///    o/__ 
        ///    |  (\
        ///.
        /// </summary>
        internal static string AnimationMessage7 {
            get {
                return ResourceManager.GetString("AnimationMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///        o _
        ///        /\ 
        ///        / |
        ///.
        /// </summary>
        internal static string AnimationMessage8 {
            get {
                return ResourceManager.GetString("AnimationMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///        \o/
        ///         |  
        ///        / \ 
        ///.
        /// </summary>
        internal static string AnimationMessage9 {
            get {
                return ResourceManager.GetString("AnimationMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now: {0}
        ///
        ///                     ,---.           ,---.
        ///                    / /&quot;`.\.--&quot;&quot;&quot;--./,&apos;&quot;\ \
        ///                    \ \    _       _    / /
        ///                     `./  / __   __ \  \,&apos;
        ///                      /    /_O)_(_O\    \
        ///                      |  .-&apos;  ___  `-.  |
        ///                   .--|       \_/       |--.
        ///                 ,&apos;    \   \   |   /   /    `.
        ///                /       `.  `--^--&apos;  ,&apos;       \
        ///             .-&quot;&quot;&quot;&quot;&quot;-.    `--.___.--&apos;     .-&quot;&quot;&quot;&quot;&quot;-.
        ///.-----------/         \------------------/         \ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BorderedMessage {
            get {
                return ResourceManager.GetString("BorderedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImageMessage {
            get {
                return ResourceManager.GetString("ImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═══╦══════════════════════════════════╦═════════╦════════════════════════╦════════════════╗
        ///║   ║                A                 ║    B    ║           C            ║       D        ║
        ///╠═══╬══════════════════════════════════╬═════════╬════════════════════════╬════════════════╣
        ///║ 1 ║ Col1                             ║ Col2    ║ Col3                   ║ Numeric Column ║
        ///║ 2 ║ Value 1                          ║ Value 2 ║ 123                    ║ 10.0           ║
        ///║ 3 ║ Separate                         ║ c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableMessage {
            get {
                return ResourceManager.GetString("TableMessage", resourceCulture);
            }
        }
    }
}
